
name: "dbt_docs_demo"
version: "1.0.0"

profile: "dbt_docs_demo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_docs_demo:
    domain_one:
      some_pipeline_one:
        +tags: ["some_tag", "bronze"]
        +docs:
          node_color: "#cc410e"
      some_pipeline_two:
        +tags: ["some_tag_two", "silver"]
        +docs:
          node_color: "#7d0ecc"
      some_destination_one:
        +tags: ["some_tag_three", "silver"]
        +docs:
          node_color: "#7d0ecc"
