name: dbt_docs_generate

on: [push]

jobs:
  dbt_docs_generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

      # pip install dbt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # dbt related commands - 
    - name: Generate dbt docs
      run: dbt docs generate --project-dir dbt_project --profiles-dir dbt_project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_dir: ./dbt_project/target
